name: "imaging-genetics"
output_dir: "master"
navbar:
  title: "3D Associations"
  left:
  - text: "Home"
   href: index.html
  - text: "HCM_3D_associations"
   href: speed-and-distance.html
output:
  html_document:
 theme: jekyll-theme-slate
